version: "3"
services:
    riott-app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "4200:4200"
        container_name: riott-app
        volumes:
            - ./:/usr/src/app
            - /usr/src/app/node_modules
